### ISSUE TITLE
Project requires a Gemfile

### ISSUE THREAD

**Issue by phlco** [melmalfa/hitch_hikely_app#1]
Be sure to add a Gemfile otherwise you won't be able to deploy!

**Comment by melmalfa** [comment]
I ran bundle init and bundle install, which created gemfile and gemfile.lock, but they're pretty empty . . .

**Comment by ghost** [comment]
I don't see them. Add and commit them, and then push it up!

**Comment by phlco** [comment]
Looks pushed up. :+1:
